name: Build Production

on:
  push:
    branches: [ "main" ]

env: 
  JOB_NAME: job/Build/job/Build%20Sistema%20Sx%20Login%20Backend
  TAG: :latest
  BRANCH: main
  REMOVE_OLDS: false

jobs:
  call-jenkins:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        status_code=$(curl --write-out %{http_code} --silent --output /dev/null --location --request POST "$JENKINS_URL/$JOB_NAME/buildWithParameters?token=$TOKEN_JOB&tag=$TAG&branch=$BRANCH&remove_old_image=$REMOVE_OLDS" \
        --header "Authorization: Basic $BASIC_AUTH")
        if [[ "$status_code" -ne 201 ]] ; then
          echo "Erro ao solicitar o build no Jenkins"
          exit 1
        else
          exit 0
        fi
      env: 
        BASIC_AUTH: ${{ secrets.BASIC_AUTH }}
        JENKINS_URL: ${{ secrets.JENKINS_URL }}
        TOKEN_JOB: ${{ secrets.TOKEN_JOB }}