name: Build and Deploy Homolog

on:
  push:
    branches: [ "develop" ]

env: 
  JOB_NAME: job/Build%20and%20Deploy/job/Build%20e%20Deploy%20Sistema%20SX%20Login%20Backend
  TAG: :develop
  BRANCH: develop
  REMOVE_OLDS: true

jobs:
  call-jenkins:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        status_code=$(curl --write-out %{http_code} --silent --output /dev/null --location --request POST "$JENKINS_URL/$JOB_NAME/build?token=$TOKEN_JOB" \
        --header "Authorization: Basic $BASIC_AUTH")
        if [[ "$status_code" -ne 201 ]] ; then
          echo "Erro ao solicitar o build no Jenkins"
          exit 1
        else
          exit 0
        fi
      env: 
        BASIC_AUTH: ${{ secrets.BASIC_AUTH }}
        JENKINS_URL: ${{ secrets.JENKINS_URL }}
        TOKEN_JOB: ${{ secrets.TOKEN_JOB }}
